logging:
  level: INFO
  loggers:
    nl.knaw.huygens: DEBUG
dbAccessFactory:
  path: /testdatabase
  db_mode: ${DB_MODE} # use "single" for a non-cluster db and "HA" for a highly availability cluster
  server_id: ${SERVER_ID} # basically a number of the server should be unique in the cluster
  server_name: ${SERVER_NAME}
  coordination_port: ${COORD_PORT}
  data_port: ${DATA_PORT}
  init_hosts: ${INIT_HOSTS} # comma separated list with the server names with the coordination port numbers, only one running host has to be configured
