logging:
  level: INFO
  loggers:
    nl.knaw.huygens: DEBUG
dbAccessFactory:
  path: /testdatabase
  #NEO4J_dbms_mode: HA
  #NEO4J_ha_serverId: 4
  #NEO4J_ha_host_coordination: instance4:5001
  #NEO4J_ha_host_data: instance4:6001
  #name: instance4
  #hostname: instance4
  #NEO4J_ha_initialHosts: instance1:5001,instance2:5001,instance3:5001,instance4:5001
